# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_goods_doodstype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='doodsType',
            new_name='goodsType',
        ),
    ]
